Comments: 'JWST SIMULATION 235M grating on NIRspec with S68N properties'
PCA:
  path: $protostars/sf/exp11/PHOENIX_JWST_PCA_Teff2700-3600.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 20.0, logAmp: -2.0, sigAmp: 1.0}
Phi_jump: {l: 0.25, logAmp: 0.01, sigAmp: 0.025}
Theta:
  A_K: 5.0
  exponentA_K: -1.85
  grid: [2900.0, 2.5, 0.01]
  logOmega: -4.5
  T_BB: 1100.0
  logOmega2: -3.5
  delR: 3000.0
  vz: 110.0
Theta_jump:
  A_K: 0.01
  exponentA_K: 0.01
  grid: [3.0, 0.003, 0.001]
  logOmega: 0.003
  T_BB: 10.0
  logOmega2: 0.002
  delR: 0.05
  vz: 0.05
Theta_priors: $protostars/sf/exp11/output/bb_absolute/run01/user_prior.py
cheb_degree: 4
cheb_jump: 0.0001
data:
  files: [$protostars/data/reduced/S68N_NIRSPEC_CO_NaI.hdf5]
  grid_name: PHOENIX
  instruments: [JWST_NIRSPEC_G235M]
  orders: [0]
grid:
  buffer: 200.0
  hdf5_path: $protostars/sf/exp11/libraries/PHOENIX_2700_3600.hdf5
  key_name: t{0:.0f}g{1:.1f}z{2:.1f}
  parname: [temp, logg, Z]
  parrange:
  - [2700, 3600]
  - [2.0, 4.0]
  - [0, 0.5]
  raw_path: $Starfish/libraries/raw/PHOENIX/
  wl_range: [17000, 30000]
name: jwst_simulation
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
